FROM node:18-alpine

WORKDIR /usr/src/app

# install only production deps
COPY package.json package-lock.json* ./
RUN npm ci --only=production || npm install --only=production

COPY . .

EXPOSE 8080

CMD ["node", "server.js"]
